export const SEARCH_NOT_FOUND = '没有找到结果'
export const NAVIGATION_HOMEPAGE = 'HOME'
export const DARK_MODE_ICON = '🌙'
export const LIGHT_MODE_ICON = '🌤️'
export const NEXT_POST_LABEL = '⏭'
export const PREVIOUS_POST_LABEL = '⏮'
export const RELATED_POST_LABEL = '相关阅读'
